/*
 * iconik_acls
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package acls

type CreateBulkAcLsSchema struct {
	GroupIds []string `json:"group_ids,omitempty"`
	IncludeAssets bool `json:"include_assets"`
	IncludeCollections bool `json:"include_collections"`
	Mode string `json:"mode,omitempty"`
	// The number of object_ids in the list is limited to a minimum of 0 and a maximum of 500
	ObjectIds []string `json:"object_ids,omitempty"`
	ObjectType string `json:"object_type,omitempty"`
	Permissions []string `json:"permissions"`
	UserIds []string `json:"user_ids,omitempty"`
}
