/*
 * iconik_acls
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package acls

type BulkAclSchema struct {
	AccessDenied []string `json:"access_denied,omitempty"`
	AccessGranted []string `json:"access_granted,omitempty"`
}
