/*
 * iconik_acls
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package acls

type DeleteAcLsSchema struct {
	GroupIds []string `json:"group_ids,omitempty"`
	// The number of object_keys in the list is limited to a minimum of 0 and a maximum of 500
	ObjectKeys []string `json:"object_keys,omitempty"`
	ObjectType string `json:"object_type,omitempty"`
	UserIds []string `json:"user_ids,omitempty"`
}
