/*
 * iconik_transcode
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package transcode

type JobSchema struct {
	AmazonRekognition bool `json:"amazon_rekognition,omitempty"`
	AnalysisData interface{} `json:"analysis_data,omitempty"`
	AnalysisQueryDefaultServiceAccount bool `json:"analysis_query_default_service_account,omitempty"`
	AssetId string `json:"asset_id,omitempty"`
	CollectionId string `json:"collection_id,omitempty"`
	CreateTranscription bool `json:"create_transcription,omitempty"`
	ForceTranscoder string `json:"force_transcoder,omitempty"`
	GoogleCloudVideoIntelligence bool `json:"google_cloud_video_intelligence,omitempty"`
	Input *InputSchema `json:"input"`
	JobId string `json:"job_id,omitempty"`
	JobSteps []JobStepSchema `json:"job_steps,omitempty"`
	Language string `json:"language,omitempty"`
	MediaInfo string `json:"media_info,omitempty"`
	Priority int32 `json:"priority,omitempty"`
	Speakers int32 `json:"speakers,omitempty"`
	Thumbnail []ThumbnailJobSchema `json:"thumbnail,omitempty"`
	Transcode []TranscodeJobSchema `json:"transcode,omitempty"`
	ValidTranscoders []TranscodersSchema `json:"valid_transcoders,omitempty"`
	VersionId string `json:"version_id,omitempty"`
}
