/*
 * iconik_transcode
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package transcode

type AnalyzeSchema struct {
	Force bool `json:"force,omitempty"`
	ServiceName string `json:"service_name,omitempty"`
}
