/*
 * iconik_transcode
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package transcode

type FacetBucketSchema struct {
	DocCount int64 `json:"doc_count,omitempty"`
	Key string `json:"key,omitempty"`
}
