/*
 * iconik_transcode
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package transcode

type TranscribeSchema struct {
	Force bool `json:"force,omitempty"`
	Language string `json:"language,omitempty"`
	ProfileId string `json:"profile_id,omitempty"`
	Speakers int32 `json:"speakers,omitempty"`
}
