/*
 * iconik_transcode
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package transcode

type TranscodersSchema struct {
	Id string `json:"id,omitempty"`
	Name string `json:"name,omitempty"`
	Settings interface{} `json:"settings,omitempty"`
	Type_ string `json:"type,omitempty"`
}
