/*
 * iconik_transcode
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package transcode

type LocalStorageFileTranscodeJobSchema struct {
	AssetId string `json:"asset_id"`
	Checksum string `json:"checksum,omitempty"`
	CollectionId string `json:"collection_id,omitempty"`
	ComponentIds []string `json:"component_ids,omitempty"`
	DirectoryPath string `json:"directory_path"`
	FileId string `json:"file_id"`
	FileSetId string `json:"file_set_id"`
	Filename string `json:"filename"`
	FormatId string `json:"format_id"`
	Id string `json:"id,omitempty"`
	JobId string `json:"job_id"`
	Priority int32 `json:"priority,omitempty"`
	Size int64 `json:"size"`
	VersionId string `json:"version_id"`
}
