/*
 * iconik_transcode
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package transcode

type EdgeTranscodeJobFieldSchema struct {
	Height int32 `json:"height,omitempty"`
	Id string `json:"id,omitempty"`
	Width int32 `json:"width,omitempty"`
}
