/*
 * iconik_transcode
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package transcode

type BulkActionSchema struct {
	ObjectIds []string `json:"object_ids"`
	ObjectType string `json:"object_type"`
}
