/*
 * iconik_transcode
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package transcode

import (
	"github.com/imtlab/iconik/shared"
)

type EdgeTranscodeWorkerSchema struct {
	Id string `json:"id,omitempty"`
	LastUpdateDate shared.Time `json:"last_update_date,omitempty"`
	Status string `json:"status"`
	StorageId string `json:"storage_id"`
}
