/*
 * iconik_transcode
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package transcode

import (
	"github.com/imtlab/go-iconik/shared"
)

type TranscodeQueueObjectSchema struct {
	DateCreated shared.Time `json:"date_created,omitempty"`
	DateUpdated shared.Time `json:"date_updated,omitempty"`
	Id string `json:"id,omitempty"`
	JobId string `json:"job_id,omitempty"`
	Priority int32 `json:"priority,omitempty"`
	RetryCount int32 `json:"retry_count,omitempty"`
	Status string `json:"status,omitempty"`
	SystemDomain string `json:"system_domain,omitempty"`
	SystemDomainId string `json:"system_domain_id,omitempty"`
	SystemDomainTimestamp float32 `json:"system_domain_timestamp,omitempty"`
	SystemName string `json:"system_name,omitempty"`
	Type_ string `json:"type,omitempty"`
	UserId string `json:"user_id,omitempty"`
}
