/*
 * iconik_metadata
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package metadata

type MetadataViewInputSchema struct {
	Description string `json:"description,omitempty"`
	Id string `json:"id,omitempty"`
	Name string `json:"name"`
	ViewFields []MetadataViewFieldSchema `json:"view_fields"`
}
