/*
 * iconik_metadata
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package metadata

type MetadataFieldMappingSchema struct {
	FieldType string `json:"field_type,omitempty"`
	MappedFieldName string `json:"mapped_field_name"`
	Name string `json:"name"`
}
