/*
 * iconik_metadata
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package metadata

type ExternalSourceFieldOptionsSchema struct {
	Label string `json:"label,omitempty"`
	Value string `json:"value,omitempty"`
}
