/*
 * iconik_metadata
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package metadata

import (
	"github.com/imtlab/go-iconik/shared"
)

type MetadataCategorySchema struct {
	DateCreated shared.Time `json:"date_created,omitempty"`
	DateModified shared.Time `json:"date_modified,omitempty"`
	Label string `json:"label"`
	Name string `json:"name"`
	ObjectType string `json:"object_type,omitempty"`
	ViewIds []string `json:"view_ids,omitempty"`
	Views []MetadataViewSchema `json:"views,omitempty"`
}
