/*
 * iconik_metadata
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package metadata

type CopySourceQueryParamsSchema struct {
	SourceObjectId string `json:"source_object_id,omitempty"`
	SourceObjectType string `json:"source_object_type,omitempty"`
	SourceVersionId string `json:"source_version_id,omitempty"`
}
