/*
 * iconik_search
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package search

import (
	"github.com/imtlab/go-iconik/shared"
)

type SearchHistorySchema struct {
	Criteria interface{} `json:"criteria"`
	DateCreated shared.Time `json:"date_created,omitempty"`
	Id string `json:"id"`
}
