/*
 * iconik_search
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package search

type DiscoveryViewSettingsSchema struct {
	EntityIds []string `json:"entity_ids"`
	Id string `json:"id,omitempty"`
	SystemDomainId string `json:"system_domain_id,omitempty"`
}
