/*
 * iconik_search
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package search

type SearchSuggestSchema struct {
	DocTypes []string `json:"doc_types,omitempty"`
	FieldName string `json:"field_name"`
	MetadataViewId string `json:"metadata_view_id,omitempty"`
	Query string `json:"query"`
}
