/*
 * iconik_search
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package search

import (
	"github.com/imtlab/iconik/shared"
)

type SavedSearchSchema struct {
	Criteria *SearchCriteriaSchema `json:"criteria"`
	DateCreated shared.Time `json:"date_created,omitempty"`
	DateModified shared.Time `json:"date_modified,omitempty"`
	GroupId string `json:"group_id,omitempty"`
	Id string `json:"id,omitempty"`
	Name string `json:"name"`
	Permissions []string `json:"permissions,omitempty"`
}
