/*
 * iconik_search
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package search

type FacetFilterSchema struct {
	Name string `json:"name"`
	ValueIn []string `json:"value_in,omitempty"`
}
