/*
 * iconik_search
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package search

import (
	"github.com/imtlab/iconik/shared"
)

type DiscoveryEntitySchema struct {
	DateCreated shared.Time `json:"date_created,omitempty"`
	DateModified shared.Time `json:"date_modified,omitempty"`
	Id string `json:"id,omitempty"`
	Metadata interface{} `json:"metadata,omitempty"`
	ObjectId string `json:"object_id,omitempty"`
	ObjectType string `json:"object_type"`
	Title string `json:"title"`
	UserId string `json:"user_id"`
}
