/*
 * iconik_search
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package search

type CriteriaTermSchema struct {
	Exists bool `json:"exists,omitempty"`
	Missing bool `json:"missing,omitempty"`
	Name string `json:"name"`
	Range_ *CriteriaRangeFilterSchema `json:"range,omitempty"`
	Value string `json:"value,omitempty"`
	ValueIn []string `json:"value_in,omitempty"`
}
