/*
 * iconik_search
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package search

import (
	"github.com/imtlab/iconik/shared"
)

type SavedSearchGroupSchema struct {
	DateCreated shared.Time `json:"date_created,omitempty"`
	DateModified shared.Time `json:"date_modified,omitempty"`
	Id string `json:"id,omitempty"`
	Name string `json:"name"`
	SystemDomainId string `json:"system_domain_id,omitempty"`
	UserId string `json:"user_id,omitempty"`
}
