/*
 * iconik_auth
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package auth

import (
	"github.com/imtlab/go-iconik/shared"
)

type ReferralCodeSchema struct {
	Code string `json:"code"`
	ManageSystemDomainId string `json:"manage_system_domain_id,omitempty"`
	ValidTo shared.Time `json:"valid_to"`
	Value float32 `json:"value"`
}
