/*
 * iconik_auth
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package auth

import (
	"github.com/imtlab/go-iconik/shared"
)

type ExternalAuthSchema struct {
	AppId string `json:"app_id,omitempty"`
	DateCreated shared.Time `json:"date_created,omitempty"`
	RedirectInfo *RedirectInfoTypeSchema `json:"redirect_info,omitempty"`
	Token string `json:"token,omitempty"`
}
