/*
 * iconik_auth
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package auth

type DomainIdentityProviderMapSchema struct {
	Domain string `json:"domain"`
	IdentityProviderId string `json:"identity_provider_id"`
	SystemDomainId string `json:"system_domain_id"`
}
