/*
 * iconik_auth
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package auth

import (
	"github.com/imtlab/iconik/shared"
)

type ApprovedAppInstanceSchema struct {
	AppId string `json:"app_id"`
	DateCreated shared.Time `json:"date_created,omitempty"`
	Id string `json:"id"`
}
