/*
 * iconik_auth
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package auth

type SimpleLoginSchema struct {
	AppName string `json:"app_name,omitempty"`
	Email string `json:"email"`
	Password string `json:"password"`
}
