/*
 * iconik_auth
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package auth

type CountrySchema struct {
	Alpha2 string `json:"alpha2,omitempty"`
	Alpha3 string `json:"alpha3,omitempty"`
	ApoliticalName string `json:"apolitical_name,omitempty"`
	Name string `json:"name"`
	Numeric string `json:"numeric,omitempty"`
}
