/*
 * iconik_auth
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package auth

type GenericSettingsSchema struct {
	CertFingerprint string `json:"cert_fingerprint,omitempty"`
	CertFingerprintAlgorithm string `json:"cert_fingerprint_algorithm,omitempty"`
	DigestAlgorithm string `json:"digest_algorithm,omitempty"`
	DomainName string `json:"domain_name,omitempty"`
	IdpEntityId string `json:"idp_entity_id"`
	IdpSlsRedirectUrl string `json:"idp_sls_redirect_url,omitempty"`
	IdpSsoPostUrl string `json:"idp_sso_post_url"`
	IdpX509cert string `json:"idp_x509cert,omitempty"`
	Name string `json:"name"`
	NameIdEncrypted bool `json:"name_id_encrypted,omitempty"`
	SignatureAlgorithm string `json:"signature_algorithm,omitempty"`
	WantAssertionsSigned bool `json:"want_assertions_signed,omitempty"`
	WantMessagesSigned bool `json:"want_messages_signed,omitempty"`
}
