/*
 * iconik_settings
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package settings

type GlobalSettingsSchema struct {
	Debug bool `json:"debug,omitempty"`
	LogLevel string `json:"log_level,omitempty"`
}
