/*
 * iconik_settings
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package settings

type GroupSettingPublicSchema struct {
	AclTemplateId string `json:"acl_template_id,omitempty"`
	AssetDefaultSections []string `json:"asset_default_sections,omitempty"`
	DateFormat string `json:"date_format,omitempty"`
	DatetimeFormat string `json:"datetime_format,omitempty"`
	DefaultUploadStorageId string `json:"default_upload_storage_id,omitempty"`
	// Grace period that indicate how long objects will live in recycle bin. Unit: hours
	DeleteGracePeriod int32 `json:"delete_grace_period,omitempty"`
	FacetFields []FacetFieldSchema `json:"facet_fields,omitempty"`
	FiltersDefaultMetadataViewId string `json:"filters_default_metadata_view_id,omitempty"`
	GroupId string `json:"group_id,omitempty"`
	HomePage string `json:"home_page,omitempty"`
	JobsDashboard *GroupSettingPublicSchemaJobsDashboard `json:"jobs_dashboard,omitempty"`
	LogoStorageId string `json:"logo_storage_id,omitempty"`
	LogoUrl string `json:"logo_url,omitempty"`
	RequiredMetadataViews []string `json:"required_metadata_views,omitempty"`
	SearchDefaultSections []string `json:"search_default_sections,omitempty"`
	SearchDisplayFields []SearchDisplayFieldSchema `json:"search_display_fields,omitempty"`
	SearchInTranscriptions bool `json:"search_in_transcriptions,omitempty"`
	// Default share expiration time that indicate how long share will be valid. Unit: days
	ShareExpirationTime int32 `json:"share_expiration_time,omitempty"`
	SystemDomainId string `json:"system_domain_id,omitempty"`
}
