/*
 * iconik_settings
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package settings

type JobsDashboardWidgetSchema struct {
	Id string `json:"id,omitempty"`
	Options *JobsWidgetOptionSchema `json:"options,omitempty"`
	Title string `json:"title,omitempty"`
	Type_ string `json:"type,omitempty"`
}
