/*
 * iconik_settings
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package settings

type GroupSettingSchema struct {
	GroupId string `json:"group_id,omitempty"`
	LogoStorageId string `json:"logo_storage_id,omitempty"`
	LogoUrl string `json:"logo_url,omitempty"`
	SystemDomainId string `json:"system_domain_id,omitempty"`
}
