/*
 * iconik_jobs
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package jobs

import (
	"github.com/imtlab/iconik/shared"
)

type JobStepUpdateSchema struct {
	DateUpdated shared.Time `json:"date_updated,omitempty"`
	ErrorMessage string `json:"error_message,omitempty"`
	Id string `json:"id,omitempty"`
	Label string `json:"label"`
	Message string `json:"message,omitempty"`
	Status string `json:"status"`
}
