/*
 * iconik_jobs
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package jobs

type JobChildProgressSchema struct {
	ProgressProcessed int64 `json:"progress_processed,omitempty"`
	ProgressTotal int64 `json:"progress_total,omitempty"`
	Status string `json:"status,omitempty"`
}
