/*
 * iconik_jobs
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package jobs

type JobsPrioritySchema struct {
	JobIds []string `json:"job_ids"`
	Priority int32 `json:"priority"`
}
