/*
 * iconik_jobs
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package jobs

type ActionContextSchema struct {
	ABORT *ActionContextValueSchema `json:"ABORT,omitempty"`
	CHANGE_PRIORITY *ActionContextValueSchema `json:"CHANGE_PRIORITY,omitempty"`
	PAUSE *ActionContextValueSchema `json:"PAUSE,omitempty"`
	RESTART *ActionContextValueSchema `json:"RESTART,omitempty"`
	RESUME *ActionContextValueSchema `json:"RESUME,omitempty"`
}
