/*
 * iconik_jobs
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package jobs

type ReindexJobSchema struct {
	SyncToAnotherDc bool `json:"sync_to_another_dc,omitempty"`
}
