/*
 * iconik_assets
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package assets

type CreateAssetVersionSchema struct {
	CopyMetadata bool `json:"copy_metadata,omitempty"`
	SourceVersionId string `json:"source_version_id,omitempty"`
	SystemDomainId string `json:"system_domain_id,omitempty"`
}
