/*
 * iconik_assets
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package assets

type BulkCollectionDeleteSchema struct {
	CollectionIds []string `json:"collection_ids"`
	IncludeAssets bool `json:"include_assets"`
	IncludeCollections bool `json:"include_collections"`
	JobId string `json:"job_id"`
}
