/*
 * iconik_assets
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package assets

type ReindexSegmentSchema struct {
	IgnoreComments bool `json:"ignore_comments,omitempty"`
	Realms []string `json:"realms,omitempty"`
	SyncToAnotherDc bool `json:"sync_to_another_dc,omitempty"`
}
