/*
 * iconik_assets
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package assets

import (
	"github.com/imtlab/go-iconik/shared"
)

type MetadataFieldValueSchema struct {
	DateCreated shared.Time `json:"date_created,omitempty"`
	FieldValues []interface{} `json:"field_values,omitempty"`
}
