/*
 * iconik_assets
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package assets

import (
	"github.com/imtlab/iconik/shared"
)

type ApprovalBySchema struct {
	ChangeDate shared.Time `json:"change_date,omitempty"`
	External string `json:"external,omitempty"`
	ObjectId string `json:"object_id,omitempty"`
	ObjectType string `json:"object_type,omitempty"`
	Status string `json:"status,omitempty"`
	User string `json:"user,omitempty"`
	VersionId string `json:"version_id,omitempty"`
}
