/*
 * iconik_assets
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package assets

type AssetVersionsSchema struct {
	AssetId string `json:"asset_id"`
	SystemDomainId string `json:"system_domain_id,omitempty"`
	Versions []EditAssetVersionSchema `json:"versions,omitempty"`
}
