/*
 * iconik_assets
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package assets

type CustomActionCallbackSchema struct {
	AssetIds []string `json:"asset_ids,omitempty"`
	CollectionIds []string `json:"collection_ids,omitempty"`
	MetadataValues string `json:"metadata_values,omitempty"`
	MetadataViewId string `json:"metadata_view_id,omitempty"`
	SavedSearchIds []string `json:"saved_search_ids,omitempty"`
}
