/*
 * iconik_assets
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package assets

type AssetHistoryBaseSchema struct {
	Id string `json:"id,omitempty"`
	JobId string `json:"job_id,omitempty"`
	OperationDescription string `json:"operation_description,omitempty"`
	OperationType string `json:"operation_type"`
	ShareId string `json:"share_id,omitempty"`
	ShareUserId string `json:"share_user_id,omitempty"`
	SystemDomainId string `json:"system_domain_id,omitempty"`
	UserId string `json:"user_id,omitempty"`
	VersionId string `json:"version_id,omitempty"`
}
