/*
 * iconik_assets
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package assets

type CollectionContentOrderingSchema struct {
	AfterObjectId string `json:"after_object_id,omitempty"`
	BeforeObjectId string `json:"before_object_id,omitempty"`
	// Position the member will be moved to. To insert athe the end send -1
	Position int32 `json:"position,omitempty"`
}
