/*
 * iconik_assets
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package assets

type UserSchema struct {
	Email string `json:"email,omitempty"`
	FirstName string `json:"first_name,omitempty"`
	Id string `json:"id,omitempty"`
	LastName string `json:"last_name,omitempty"`
	Photo string `json:"photo,omitempty"`
	PhotoBig string `json:"photo_big,omitempty"`
	PhotoSmall string `json:"photo_small,omitempty"`
}
