/*
 * iconik_assets
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package assets

import (
	"github.com/imtlab/iconik/shared"
)

type ShareUserSchema struct {
	AccessCount int32 `json:"access_count,omitempty"`
	Email string `json:"email"`
	FirstName string `json:"first_name,omitempty"`
	Id string `json:"id,omitempty"`
	LastAccessDate shared.Time `json:"last_access_date,omitempty"`
	LastName string `json:"last_name,omitempty"`
	ObjectId string `json:"object_id,omitempty"`
	ObjectType string `json:"object_type,omitempty"`
	Password string `json:"password,omitempty"`
	Photo string `json:"photo,omitempty"`
	PhotoBig string `json:"photo_big,omitempty"`
	PhotoSmall string `json:"photo_small,omitempty"`
	ShareId string `json:"share_id,omitempty"`
}
