/*
 * iconik_assets
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package assets

import (
	"github.com/imtlab/iconik/shared"
)

type AssetEditSchema struct {
	AnalyzeStatus string `json:"analyze_status,omitempty"`
	ArchiveStatus string `json:"archive_status,omitempty"`
	Category string `json:"category,omitempty"`
	CreatedByUser string `json:"created_by_user,omitempty"`
	CreatedByUserInfo *UserSchema `json:"created_by_user_info,omitempty"`
	CustomKeyframe string `json:"custom_keyframe,omitempty"`
	CustomPoster string `json:"custom_poster,omitempty"`
	DateCreated shared.Time `json:"date_created,omitempty"`
	DateDeleted shared.Time `json:"date_deleted,omitempty"`
	DateImported shared.Time `json:"date_imported,omitempty"`
	DateModified shared.Time `json:"date_modified,omitempty"`
	DeletedByUser string `json:"deleted_by_user,omitempty"`
	DeletedByUserInfo *UserSchema `json:"deleted_by_user_info,omitempty"`
	ExternalId string `json:"external_id,omitempty"`
	Id string `json:"id"`
	IsBlocked bool `json:"is_blocked,omitempty"`
	IsOnline bool `json:"is_online,omitempty"`
	Status string `json:"status,omitempty"`
	Title string `json:"title,omitempty"`
	Type_ string `json:"type,omitempty"`
	UpdatedByUser string `json:"updated_by_user,omitempty"`
	UpdatedByUserInfo *UserSchema `json:"updated_by_user_info,omitempty"`
	Warning string `json:"warning,omitempty"`
}
