/*
 * iconik_assets
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package assets

import (
	"github.com/imtlab/iconik/shared"
)

type EditAssetVersionSchema struct {
	AnalyzeStatus string `json:"analyze_status,omitempty"`
	ArchiveStatus string `json:"archive_status,omitempty"`
	CreatedByUser string `json:"created_by_user,omitempty"`
	CreatedByUserInfo *UserSchema `json:"created_by_user_info,omitempty"`
	DateCreated shared.Time `json:"date_created,omitempty"`
	Id string `json:"id"`
	IsOnline bool `json:"is_online,omitempty"`
	Status string `json:"status,omitempty"`
	TranscribeStatus string `json:"transcribe_status,omitempty"`
}
