/*
 * iconik_assets
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package assets

type CollectionContentInfoSchema struct {
	AssetsCount int32 `json:"assets_count,omitempty"`
	CollectionsCount int32 `json:"collections_count,omitempty"`
}
