/*
 * iconik_users
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package users

type UserSamlUpdateSchema struct {
	FirstName string `json:"first_name,omitempty"`
	GroupNames []string `json:"group_names,omitempty"`
	IdentityProviderId string `json:"identity_provider_id,omitempty"`
	LastName string `json:"last_name,omitempty"`
}
