/*
 * iconik_users
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package users

type InlineResponse200 struct {
	// Url for the group logo
	Logo string `json:"logo,omitempty"`
}
