/*
 * iconik_users
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package users

type InlineResponse2001 struct {
	// Url for the user original photo
	Photo string `json:"photo,omitempty"`
	// Url for the user re-sized big photo
	PhotoBig string `json:"photo_big,omitempty"`
	// Url for the user re-sized small photo
	PhotoSmall string `json:"photo_small,omitempty"`
}
