/*
 * iconik_files
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package files

type MultipartUploadCleanupSchema struct {
	PartsGroupNumber int64 `json:"parts_group_number,omitempty"`
	PartsNumber int64 `json:"parts_number"`
	Temporary bool `json:"temporary,omitempty"`
}
