/*
 * iconik_files
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package files

type TranscoderByStorageReadSchema struct {
	Id string `json:"id,omitempty"`
	Name string `json:"name,omitempty"`
	Settings string `json:"settings,omitempty"`
	StorageId string `json:"storage_id,omitempty"`
	Type_ string `json:"type,omitempty"`
}
