/*
 * iconik_files
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package files

type MultiPartUploadComposeUrlSchema struct {
	ComposeUrl string `json:"compose_url,omitempty"`
	DeleteUrl string `json:"delete_url,omitempty"`
	Key string `json:"key,omitempty"`
	Url string `json:"url,omitempty"`
}
