/*
 * iconik_files
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package files

type AnalysisProfileServiceIdSchema struct {
	AnalysisServiceAccountId string `json:"analysis_service_account_id"`
}
