/*
 * iconik_files
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package files

type FormatArchiveSchema struct {
	DeleteOriginal bool `json:"delete_original,omitempty"`
	DestinationDirectoryPath string `json:"destination_directory_path,omitempty"`
	DestinationFileSetName string `json:"destination_file_set_name,omitempty"`
	DestinationStorageId string `json:"destination_storage_id,omitempty"`
	DestinationStorageMethod string `json:"destination_storage_method,omitempty"`
	FormatId string `json:"format_id,omitempty"`
	OriginalFileSetId string `json:"original_file_set_id,omitempty"`
}
