/*
 * iconik_files
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package files

type StorageScanSchema struct {
	Files []string `json:"files,omitempty"`
	// Will force scanning even if the scan is already active if any of `paths` or `files` are specified.
	IgnoreAlreadyActive bool `json:"ignore_already_active,omitempty"`
	Paths []string `json:"paths,omitempty"`
}
