/*
 * iconik_files
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package files

type ExportLocationSchema struct {
	Description string `json:"description,omitempty"`
	ExportMetadata bool `json:"export_metadata,omitempty"`
	ExportOriginal bool `json:"export_original,omitempty"`
	ExportPosters bool `json:"export_posters,omitempty"`
	ExportToAssetFolder bool `json:"export_to_asset_folder,omitempty"`
	ExportTranscriptions bool `json:"export_transcriptions,omitempty"`
	Id string `json:"id,omitempty"`
	MetadataFormat string `json:"metadata_format,omitempty"`
	MetadataView string `json:"metadata_view,omitempty"`
	Name string `json:"name"`
	Path string `json:"path"`
	StorageId string `json:"storage_id"`
	SystemDomainId string `json:"system_domain_id,omitempty"`
	TranscodeProfileIds []string `json:"transcode_profile_ids,omitempty"`
	TranscriptionFormat string `json:"transcription_format,omitempty"`
}
