/*
 * iconik_files
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package files

type AssetBatchExportItemSchema struct {
	AssetId string `json:"asset_id"`
	FileName string `json:"file_name,omitempty"`
	FormatId string `json:"format_id,omitempty"`
}
