/*
 * iconik_files
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package files

type EditProxySettingsSchema struct {
	Bitrate int32 `json:"bitrate,omitempty"`
	Codec string `json:"codec,omitempty"`
	Data string `json:"data,omitempty"`
	DeleteAfterUpload bool `json:"delete_after_upload,omitempty"`
	DestinationPath string `json:"destination_path,omitempty"`
	ExcludePatterns string `json:"exclude_patterns,omitempty"`
	Height int32 `json:"height"`
	IncludePatterns string `json:"include_patterns,omitempty"`
	Local bool `json:"local,omitempty"`
	MinHeight int32 `json:"min_height,omitempty"`
	MinWidth int32 `json:"min_width,omitempty"`
	StorageId string `json:"storage_id,omitempty"`
	Width int32 `json:"width"`
}
