/*
 * iconik_files
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package files

type ProxyUpdateSchema struct {
	AssetId string `json:"asset_id,omitempty"`
	BitRate int32 `json:"bit_rate,omitempty"`
	Codec string `json:"codec,omitempty"`
	Filename string `json:"filename,omitempty"`
	Format string `json:"format,omitempty"`
	FrameRate string `json:"frame_rate,omitempty"`
	Id string `json:"id,omitempty"`
	IsDropFrame bool `json:"is_drop_frame,omitempty"`
	IsPublic bool `json:"is_public,omitempty"`
	Name string `json:"name,omitempty"`
	Resolution *ResolutionTypeSchema `json:"resolution,omitempty"`
	Rotation int32 `json:"rotation,omitempty"`
	Size int64 `json:"size,omitempty"`
	StartTimeCode string `json:"start_time_code,omitempty"`
	Status string `json:"status,omitempty"`
	StorageId string `json:"storage_id,omitempty"`
	Url string `json:"url,omitempty"`
	VersionId string `json:"version_id,omitempty"`
}
