/*
 * iconik_files
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package files

type FileShareUploadEditSchema struct {
	Size int64 `json:"size,omitempty"`
	Status string `json:"status,omitempty"`
}
