/*
 * iconik_files
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package files

type SubtitleRequestSchema struct {
	CreateTranscription bool `json:"create_transcription,omitempty"`
	Priority int32 `json:"priority,omitempty"`
}
