/*
 * iconik_files
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package files

type EncodingComSettingsSchema struct {
	Local bool `json:"local,omitempty"`
	UserId string `json:"user_id"`
	UserKey string `json:"user_key"`
}
