/*
 * iconik_files
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package files

type TimeBaseTypeSchema struct {
	Denominator int32 `json:"denominator,omitempty"`
	Numerator int32 `json:"numerator,omitempty"`
}
