/*
 * iconik_files
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package files

type ComponentSchema struct {
	Id string `json:"id,omitempty"`
	Metadata interface{} `json:"metadata,omitempty"`
	Name string `json:"name"`
	Type_ string `json:"type"`
}
