/*
 * iconik_files
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package files

type ResolutionTypeSchema struct {
	Height int32 `json:"height,omitempty"`
	Width int32 `json:"width,omitempty"`
}
