/*
 * iconik_files
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package files

type SubtitleSchema struct {
	AssetId string `json:"asset_id"`
	ClosedCaptions bool `json:"closed_captions"`
	Content string `json:"content,omitempty"`
	FormatId string `json:"format_id"`
	Id string `json:"id"`
	Language string `json:"language"`
	Name string `json:"name,omitempty"`
	VersionId string `json:"version_id,omitempty"`
}
