/*
 * iconik_files
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package files

type MultiPartUploadUrlSchema struct {
	DeleteUrl string `json:"delete_url,omitempty"`
	DownloadUrl string `json:"download_url,omitempty"`
	Key string `json:"key,omitempty"`
	Number int32 `json:"number,omitempty"`
	Url string `json:"url,omitempty"`
}
