/*
 * iconik_files
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package files

type KeyframeBaseSchema struct {
	Filename string `json:"filename,omitempty"`
	Format string `json:"format,omitempty"`
	IsCustomKeyframe bool `json:"is_custom_keyframe,omitempty"`
	IsPublic bool `json:"is_public,omitempty"`
	Name string `json:"name,omitempty"`
	Resolution *ResolutionTypeSchema `json:"resolution,omitempty"`
	Rotation int32 `json:"rotation,omitempty"`
	Size int64 `json:"size,omitempty"`
	Status string `json:"status,omitempty"`
	TimeCode *TimeCodeTypeSchema `json:"time_code,omitempty"`
	Type_ string `json:"type"`
	Url string `json:"url,omitempty"`
}
