/*
 * iconik_files
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package files

import (
	"github.com/imtlab/iconik/shared"
)

type TemporaryFileSetSchema struct {
	AssetId string `json:"asset_id,omitempty"`
	BaseDir string `json:"base_dir"`
	ComponentIds []string `json:"component_ids"`
	DateDeleted shared.Time `json:"date_deleted,omitempty"`
	DeletedByUser string `json:"deleted_by_user,omitempty"`
	FormatId string `json:"format_id"`
	Id string `json:"id,omitempty"`
	IsArchive bool `json:"is_archive,omitempty"`
	JobId string `json:"job_id"`
	Name string `json:"name"`
	OriginalStorageId string `json:"original_storage_id,omitempty"`
	Status string `json:"status,omitempty"`
	StorageId string `json:"storage_id,omitempty"`
	VersionId string `json:"version_id,omitempty"`
}
