/*
 * iconik_files
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package files

type AnalysisAmazonRekognitionSettingsSchema struct {
	AccessKey string `json:"access_key"`
	Bucket string `json:"bucket"`
	Endpoint string `json:"endpoint"`
	IsSystem bool `json:"is_system,omitempty"`
	Path string `json:"path"`
	Region string `json:"region"`
	SecretKey string `json:"secret_key"`
}
