/*
 * iconik_files
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package files

import (
	"github.com/imtlab/go-iconik/shared"
)

type IconikStorageGatewayEventSchema struct {
	Data interface{} `json:"data,omitempty"`
	DateCreated shared.Time `json:"date_created,omitempty"`
	Id string `json:"id,omitempty"`
	Type_ string `json:"type"`
}
