/*
 * iconik_files
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package files

type IconikEdgeTranscoderSchema struct {
	Local bool `json:"local,omitempty"`
	MaxTranscodingJobs int32 `json:"max_transcoding_jobs,omitempty"`
}
