/*
 * iconik_files
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package files

type FileDeletionFromLocalStorageSchema struct {
	DirectoryPath string `json:"directory_path,omitempty"`
	FileId string `json:"file_id"`
	Filename string `json:"filename"`
	Id string `json:"id,omitempty"`
	JobId string `json:"job_id"`
	KeepSource bool `json:"keep_source,omitempty"`
	StorageId string `json:"storage_id"`
}
