/*
 * iconik_files
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package files

type MoveAssetResourceSchema struct {
	DestinationAssetId string `json:"destination_asset_id"`
	DestinationVersionId string `json:"destination_version_id"`
	SourceVersionId string `json:"source_version_id"`
}
