/*
 * iconik_files
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package files

type BulkTranscodeSchema struct {
	FormatName string `json:"format_name,omitempty"`
	ObjectIds []string `json:"object_ids"`
	ObjectType string `json:"object_type"`
	PreferAnyCloud bool `json:"prefer_any_cloud,omitempty"`
	PreferredStorageId string `json:"preferred_storage_id,omitempty"`
	PreferredStorageMethod string `json:"preferred_storage_method,omitempty"`
	Priority int32 `json:"priority,omitempty"`
}
