/*
 * iconik_files
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package files

type TranscodeRequestSchema struct {
	Priority int32 `json:"priority,omitempty"`
	SetAsCustomKeyframe bool `json:"set_as_custom_keyframe,omitempty"`
	UpdateProxyMediainfo bool `json:"update_proxy_mediainfo,omitempty"`
	UseStorageTranscodeIgnorePattern bool `json:"use_storage_transcode_ignore_pattern,omitempty"`
}
