/*
 * iconik_files
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package files

type AnalysisRevAiSettingsSchema struct {
	AccessToken string `json:"access_token"`
	IsSystem bool `json:"is_system,omitempty"`
}
