/*
 * iconik_files
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package files

type EditProxySchema struct {
	DirectoryPath string `json:"directory_path"`
	ForceStorageId bool `json:"force_storage_id,omitempty"`
	Height int32 `json:"height"`
	IgnoreTranscoderSettings bool `json:"ignore_transcoder_settings,omitempty"`
	Name string `json:"name"`
	StorageId string `json:"storage_id"`
	VersionId string `json:"version_id"`
	Width int32 `json:"width"`
}
