/*
 * iconik_files
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package files

type FFmpegSettingsSchema struct {
	Bitrate int32 `json:"bitrate,omitempty"`
	Data string `json:"data,omitempty"`
	EditProxyFolder string `json:"edit_proxy_folder,omitempty"`
	Local bool `json:"local,omitempty"`
	OverlayCoordinates string `json:"overlay_coordinates,omitempty"`
	OverlayUrl string `json:"overlay_url,omitempty"`
	Width int32 `json:"width,omitempty"`
}
