/*
 * iconik_files
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package files

type MultipartB2StartUpload struct {
	AuthorizationToken string `json:"authorization_token,omitempty"`
	Error_ string `json:"error,omitempty"`
	ErrorCode string `json:"error_code,omitempty"`
	Status string `json:"status,omitempty"`
	UploadFileId string `json:"upload_file_id,omitempty"`
	UploadUrl string `json:"upload_url,omitempty"`
}
