/*
 * iconik_files
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package files

type ImageMagickSettingsSchema struct {
	Data string `json:"data,omitempty"`
	Local bool `json:"local,omitempty"`
	OverlayCoordinates string `json:"overlay_coordinates,omitempty"`
	OverlayUrl string `json:"overlay_url,omitempty"`
}
