/*
 * iconik_users_notifications
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package usersnotifications

import (
	"github.com/imtlab/go-iconik/shared"
)

type SubscriptionSchema struct {
	DateCreated shared.Time `json:"date_created,omitempty"`
	DateModified shared.Time `json:"date_modified,omitempty"`
	EventType string `json:"event_type,omitempty"`
	Id string `json:"id,omitempty"`
	ObjectId string `json:"object_id,omitempty"`
	ObjectType string `json:"object_type"`
	SubObjectId string `json:"sub_object_id,omitempty"`
	SubObjectType string `json:"sub_object_type,omitempty"`
	SystemDomainId string `json:"system_domain_id,omitempty"`
	UserId string `json:"user_id,omitempty"`
}
