/*
 * iconik_users_notifications
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package usersnotifications

type NotificationSettingSchema struct {
	Enabled bool `json:"enabled"`
	EventType string `json:"event_type"`
	ObjectType string `json:"object_type"`
	Protocol string `json:"protocol,omitempty"`
	RecipientId string `json:"recipient_id"`
	Settings interface{} `json:"settings,omitempty"`
	SubObjectType string `json:"sub_object_type,omitempty"`
	SystemDomainId string `json:"system_domain_id,omitempty"`
}
