/*
 * iconik_stats
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package stats

type CreditsSchema struct {
	Country string `json:"country,omitempty"`
	Credits int32 `json:"credits"`
	Currency string `json:"currency,omitempty"`
	Total float32 `json:"total,omitempty"`
	Vat int32 `json:"vat,omitempty"`
}
