/*
 * iconik_stats
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package stats

import (
	"github.com/imtlab/iconik/shared"
)

type StorageAccessSchema struct {
	BucketName string `json:"bucket_name"`
	BytesReceived int64 `json:"bytes_received,omitempty"`
	BytesSent int64 `json:"bytes_sent,omitempty"`
	Date shared.Time `json:"date,omitempty"`
	Id string `json:"id,omitempty"`
	OperationType string `json:"operation_type"`
	Operations int32 `json:"operations,omitempty"`
	StorageType string `json:"storage_type"`
	SystemDomainId string `json:"system_domain_id,omitempty"`
	SystemName string `json:"system_name"`
}
