/*
 * iconik_stats
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package stats

type BillingStatsSchema struct {
	CurrentBalance float32 `json:"current_balance,omitempty"`
	InvoiceEndOfMonth bool `json:"invoice_end_of_month,omitempty"`
	NewBillingEnabled bool `json:"new_billing_enabled,omitempty"`
	StripeId bool `json:"stripe_id,omitempty"`
	SystemDomainStatus string `json:"system_domain_status,omitempty"`
	SystemDomainType string `json:"system_domain_type"`
	SystemDomainWarningMessage string `json:"system_domain_warning_message"`
}
