/*
 * iconik_stats
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package stats

import (
	"github.com/imtlab/go-iconik/shared"
)

type StorageUsageSchema struct {
	BucketName string `json:"bucket_name"`
	BytesStored int64 `json:"bytes_stored,omitempty"`
	Date shared.Time `json:"date,omitempty"`
	Id string `json:"id,omitempty"`
	StorageType string `json:"storage_type"`
	SystemDomainId string `json:"system_domain_id,omitempty"`
	SystemName string `json:"system_name"`
}
