/*
 * iconik_stats
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package stats

import (
	"github.com/imtlab/iconik/shared"
)

type TranscoderUsageSchema struct {
	AdjustedDurationSeconds int64 `json:"adjusted_duration_seconds,omitempty"`
	Date string `json:"date,omitempty"`
	DestinationBytes int64 `json:"destination_bytes,omitempty"`
	DurationSeconds int64 `json:"duration_seconds,omitempty"`
	Id string `json:"id,omitempty"`
	IsUserTranscoder bool `json:"is_user_transcoder,omitempty"`
	JobId string `json:"job_id,omitempty"`
	ObjectId string `json:"object_id,omitempty"`
	ObjectType string `json:"object_type,omitempty"`
	OperationType string `json:"operation_type,omitempty"`
	PercentDone int32 `json:"percent_done,omitempty"`
	SourceBytes int64 `json:"source_bytes,omitempty"`
	Status string `json:"status"`
	SystemDomainId string `json:"system_domain_id,omitempty"`
	SystemName string `json:"system_name"`
	Time shared.Time `json:"time,omitempty"`
	TranscoderType string `json:"transcoder_type"`
}
