/*
 * iconik_stats
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package stats

import (
	"github.com/imtlab/iconik/shared"
)

type DateFilterSchema struct {
	FromDate shared.Time `json:"from_date,omitempty"`
	ToDate shared.Time `json:"to_date,omitempty"`
}
