/*
 * iconik_stats
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package stats

type StorageAccessElasticSchema struct {
	BucketName string `json:"bucket_name,omitempty"`
	BytesReceived int64 `json:"bytes_received,omitempty"`
	BytesSent int64 `json:"bytes_sent,omitempty"`
	Date string `json:"date,omitempty"`
	Id string `json:"id,omitempty"`
	Operations int32 `json:"operations,omitempty"`
	SystemDomainId string `json:"system_domain_id,omitempty"`
}
