/*
 * iconik_stats
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package stats

type BillingCustomerSchema struct {
	BusinessVatId string `json:"business_vat_id,omitempty"`
	Email string `json:"email,omitempty"`
	EnableSubscription bool `json:"enable_subscription,omitempty"`
	Shipping *BillingCustomerShippingSchema `json:"shipping"`
}
