/*
 * iconik_stats
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package stats

type BillingCreditsVerifySchema struct {
	Charge string `json:"charge,omitempty"`
	InvoiceId string `json:"invoice_id"`
	SystemDomainId string `json:"system_domain_id,omitempty"`
}
