/*
 * iconik_stats
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package stats

type BillingCustomerShippingAddressSchema struct {
	City string `json:"city"`
	Country string `json:"country"`
	Line1 string `json:"line1"`
	Line2 string `json:"line2,omitempty"`
	PostalCode string `json:"postal_code"`
	State string `json:"state,omitempty"`
}
