/*
 * iconik_stats
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package stats

type UserUsagesElasticSchema struct {
	Count int64 `json:"count,omitempty"`
	Date string `json:"date,omitempty"`
	Id string `json:"id,omitempty"`
	SystemDomainId string `json:"system_domain_id,omitempty"`
	Type_ string `json:"type,omitempty"`
	UserEmail string `json:"user_email,omitempty"`
	UserId string `json:"user_id,omitempty"`
	UserName string `json:"user_name,omitempty"`
}
