/*
 * iconik_stats
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package stats

type UserUsagesDetailedSchema struct {
	Date string `json:"date,omitempty"`
	SystemDomainId string `json:"system_domain_id,omitempty"`
	Type_ string `json:"type,omitempty"`
	UserId string `json:"user_id,omitempty"`
}
