/*
 * iconik_stats
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package stats

import (
	"github.com/imtlab/iconik/shared"
)

type AssetUsageSchema struct {
	AssetId string `json:"asset_id"`
	AssetType string `json:"asset_type,omitempty"`
	Date string `json:"date,omitempty"`
	Id string `json:"id,omitempty"`
	Metadata string `json:"metadata,omitempty"`
	OperationSource string `json:"operation_source,omitempty"`
	OperationType string `json:"operation_type"`
	SystemDomainId string `json:"system_domain_id,omitempty"`
	SystemName string `json:"system_name"`
	Time shared.Time `json:"time,omitempty"`
	UserId string `json:"user_id"`
}
