/*
 * iconik_stats
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package stats

type TranscoderUsagesElasticSchema struct {
	Count int64 `json:"count,omitempty"`
	Date string `json:"date,omitempty"`
	DestinationBytes int64 `json:"destination_bytes,omitempty"`
	DurationSeconds int64 `json:"duration_seconds,omitempty"`
	Id string `json:"id,omitempty"`
	IsUserTranscoder bool `json:"is_user_transcoder,omitempty"`
	OperationType string `json:"operation_type,omitempty"`
	SourceBytes int64 `json:"source_bytes,omitempty"`
	SystemDomainId string `json:"system_domain_id,omitempty"`
	TranscoderType string `json:"transcoder_type"`
}
