/*
 * iconik_stats
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package stats

import (
	"github.com/imtlab/iconik/shared"
)

type UserAuditSchema struct {
	AppId string `json:"app_id,omitempty"`
	ClientIp string `json:"client_ip,omitempty"`
	Date string `json:"date,omitempty"`
	Id string `json:"id,omitempty"`
	IsActingAsUser bool `json:"is_acting_as_user,omitempty"`
	Metadata string `json:"metadata,omitempty"`
	OperationResult int64 `json:"operation_result,omitempty"`
	OperationType string `json:"operation_type"`
	OriginalUserId string `json:"original_user_id,omitempty"`
	RequestId string `json:"request_id,omitempty"`
	Resource string `json:"resource,omitempty"`
	ShareId string `json:"share_id,omitempty"`
	ShareUserId string `json:"share_user_id,omitempty"`
	Sudo bool `json:"sudo,omitempty"`
	SystemDomainId string `json:"system_domain_id,omitempty"`
	SystemName string `json:"system_name"`
	Time shared.Time `json:"time,omitempty"`
	UserId string `json:"user_id,omitempty"`
}
